### PR TITLE
Fix sequencesgrid spacing bug

### LINKED ISSUE #4921: SequencesGrid should probably use grid instead of flexbox
When there are exactly two sequences in a row, they are too spaced out:

Screen Shot 2022-05-13 at 4 11 29 PM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202276772599830) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by leoshatrushin**
Fixes #4921 by changing SequencesGrid to use a 3-column grid instead of flexbow row-wrap. At the legacy small breakpoint, changes to a centered 1 column grid.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205773147183177) by [Unito](https://www.unito.io)

### CODE REVIEW

File: packages/lesswrong/components/sequences/SequencesGridItem.tsx [hunk 1]
```diff
@@ -10,10 +10,9 @@ const styles = (theme: ThemeType): JssStyles => ({
   root: {
     ...theme.typography.postStyle,
 
-    width: "calc(33% - 5px)",
     boxShadow: theme.palette.boxShadow.default,
     paddingBottom: 0,
-    marginBottom: 10,
+    marginBottom: 0,
```
Comment (jpaddison3) [inline packages/lesswrong/components/sequences/SequencesGridItem.tsx:15]:
```suggestion
```

It appears you can get rid of this.

**Review by jpaddison3 — APPROVED** [review]
LGTM, thanks so much!
